export const SEED_CARDS: { deck: string; front: string; back: string; tags: string }[] = [
  {
    deck: "DSA / LeetCode",
    front: "Two Sum — Pattern? Approach? Complexity?",
    back: "**Pattern:** Hash Map\n\n**Approach:** Iterate, for each `x` check if `target - x` in map → return indices. Else store `x -> i`.\n\n**Complexity:** `O(n)` time, `O(n)` space.\n\n**Trap:** Duplicate values, return indices not values.",
    tags: "array, hashmap, easy",
  },
  {
    deck: "DSA / LeetCode",
    front: "Sliding Window — When to use? Example problem?",
    back: "**When:** Contiguous subarray/substring with constraint (max/min length, sum, distinct `k`).\n\n**Template:** `left=0, for right... expand, while invalid shrink left, update ans`.\n\n**Ex:** Longest substring without repeating characters, Minimum window substring.",
    tags: "sliding-window, pattern",
  },
  {
    deck: "DSA / LeetCode",
    front: "DFS vs BFS — tradeoffs in graphs/trees?",
    back: "**DFS:** Stack/recursion, `O(h)` space, good for path existence, topological sort. May overflow.\n\n**BFS:** Queue, `O(w)` space, good for shortest path unweighted. Level order.\n\n**Both `O(V+E)`**.",
    tags: "graph, traversal",
  },
  {
    deck: "System Design Concepts",
    front: "CAP Theorem — explain with example",
    back: "**C**onsistency, **A**vailability, **P**artition tolerance — pick 2. In partition, choose CP (e.g., ZK) or AP (e.g., Dynamo). RDBMS is CA only without partition.\n\n**Principal nuance:** In practice it's latency vs consistency under partition.",
    tags: "cap, distributed",
  },
  {
    deck: "System Design Concepts",
    front: "Cache — Cache-Aside vs Write-Through vs Write-Behind?",
    back: "**Cache-Aside:** App loads DB on miss, app writes DB then invalidates. Simple, stale risk.\n**Write-Through:** Write to cache + DB synchronously. Strong consistency, write latency.\n**Write-Behind:** Async DB write. Fast but loss risk.\n\n**Principal:** Choose based on read/write ratio + durability.",
    tags: "cache, pattern",
  },
  {
    deck: "System Design Concepts",
    front: "Sharding vs Partitioning — how to pick shard key?",
    back: "**Goal:** Even distribution, avoid hot shard, support queries.\n**Good key:** High cardinality, uniform (user_id). Avoid low cardinality (country).\n**Strategies:** Hash (even), Range (range queries), Consistent hash (re-balance).\n**Follow-up:** How to handle re-sharding? Double-write.",
    tags: "sharding, database",
  },
  {
    deck: "System Design Use Cases",
    front: "Design URL Shortener — FR/NFR, scale numbers?",
    back: "**FR:** Shorten, redirect, expiry, custom alias.\n**NFR:** ~100M URLs/day, read-heavy 100:1, <100ms redirect, 5yr retention.\n**Scale:** 500M URLs/mo → ~100B in 5y → ~5TB metadata.\n**HLD:** API → App → Cache (Redis) → DB (sharded KV by hash) + Base62 vs random 7-char.",
    tags: "system-design, shortener",
  },
  {
    deck: "System Design Use Cases",
    front: "Design Rate Limiter — algorithms?",
    back: "**Token Bucket:** Burst-friendly. **Leaky Bucket:** Smooth. **Fixed Window:** Simple but boundary burst. **Sliding Window Log/Counter:** Precise, more memory.\n\n**Distributed:** Redis + Lua script, `SET key count EX window`. **Principal add:** Per-user vs per-IP vs global, response headers `X-RateLimit-*`.",
    tags: "system-design, rate-limiter",
  },
  {
    deck: "AI Concepts",
    front: "RAG — components and failure modes?",
    back: "**Components:** Chunker → Embedder → Vector DB → Retriever (top-k) → LLM with context.\n**Failures:** Bad chunking (loss of context), poor recall (embedding drift), LLM ignores retrieved docs, stale index.\n**Fix:** Hybrid search (BM25+vector), reranker, eval with hit-rate/MRR.",
    tags: "rag, llm",
  },
  {
    deck: "AI Concepts",
    front: "Vector DB — HNSW vs IVF? When to use which?",
    back: "**HNSW:** Graph, fast query (<10ms), high recall, high memory. Good for <10M vectors.\n**IVF:** Cluster, lower memory, slower, needs nprobe tuning. Better for >100M.\n**Principal:** Measure recall@k vs latency for your n.",
    tags: "vector-db, retrieval",
  },
  {
    deck: "AI Use Cases",
    front: "Design AI Search (like Perplexity) — flow?",
    back: "**Flow:** Query → Query rewrite → Hybrid retrieval (web + vector) → Rerank → LLM synthesize with citations → Guardrails.\n**Key:** Freshness (crawl), attribution, cost (cache embeddings), eval (answer relevance).",
    tags: "ai-system, search",
  },
  {
    deck: "Behavioral",
    front: "Tell me about your best project — STAR (2 min)",
    back: "**S:** Context: scaling X from 1k→1M QPS, team of 5, 3-month deadline.\n**T:** Your ownership: design, unblock.\n**A:** Tradeoffs: chose event-driven over sync, mentored 2 engineers, negotiated scope.\n**R:** Impact: -40% latency, +$Y revenue, lesson: influence without authority.",
    tags: "behavioral, STAR",
  },
  {
    deck: "Behavioral",
    front: "Conflict with peer/stakeholder — how did you handle?",
    back: "**STAR:** Disagreement on tech choice. Listened 1:1, data over opinion, ran spike/ADR, proposed 2 options with tradeoffs, escalated with recommendation not complaint. **Principal lens:** Disagree & commit, earn trust.",
    tags: "behavioral, leadership",
  },
];
export const BLIND75_SEED: { deck: string; front: string; back: string; tags: string }[] = [
  { deck: "DSA / LeetCode", front: "128. Longest Consecutive Sequence — Med. (47.2%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/longest-consecutive-sequence\n\n**Difficulty:** Med. | **Acceptance:** 47.2%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "1. Two Sum — Easy (58.1%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/two-sum\n\n**Difficulty:** Easy | **Acceptance:** 58.1%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, easy, leetcode" },
  { deck: "DSA / LeetCode", front: "3. Longest Substring Without Repeating Characters — Med. (39.9%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/longest-substring-without-repeating-characters\n\n**Difficulty:** Med. | **Acceptance:** 39.9%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "5. Longest Palindromic Substring — Med. (38.5%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/longest-palindromic-substring\n\n**Difficulty:** Med. | **Acceptance:** 38.5%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "133. Clone Graph — Med. (66.1%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/clone-graph\n\n**Difficulty:** Med. | **Acceptance:** 66.1%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "261. Graph Valid Tree — Med. (50.1%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/graph-valid-tree\n\n**Difficulty:** Med. | **Acceptance:** 50.1%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "647. Palindromic Substrings — Med. (73.2%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/palindromic-substrings\n\n**Difficulty:** Med. | **Acceptance:** 73.2%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "11. Container With Most Water — Med. (60.7%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/container-with-most-water\n\n**Difficulty:** Med. | **Acceptance:** 60.7%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "139. Word Break — Med. (49.8%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/word-break\n\n**Difficulty:** Med. | **Acceptance:** 49.8%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "141. Linked List Cycle — Easy (55.0%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/linked-list-cycle\n\n**Difficulty:** Easy | **Acceptance:** 55.0%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, easy, leetcode" },
  { deck: "DSA / LeetCode", front: "268. Missing Number — Easy (72.6%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/missing-number\n\n**Difficulty:** Easy | **Acceptance:** 72.6%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, easy, leetcode" },
  { deck: "DSA / LeetCode", front: "15. 3Sum — Med. (39.8%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/3sum\n\n**Difficulty:** Med. | **Acceptance:** 39.8%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "143. Reorder List — Med. (66.1%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/reorder-list\n\n**Difficulty:** Med. | **Acceptance:** 66.1%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "269. Alien Dictionary — Hard (37.3%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/alien-dictionary\n\n**Difficulty:** Hard | **Acceptance:** 37.3%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, hard, leetcode" },
  { deck: "DSA / LeetCode", front: "271. Encode and Decode Strings — Med. (51.9%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/encode-and-decode-strings\n\n**Difficulty:** Med. | **Acceptance:** 51.9%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "19. Remove Nth Node From End of List — Med. (52.5%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/remove-nth-node-from-end-of-list\n\n**Difficulty:** Med. | **Acceptance:** 52.5%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "20. Valid Parentheses — Easy (44.8%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/valid-parentheses\n\n**Difficulty:** Easy | **Acceptance:** 44.8%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, easy, leetcode" },
  { deck: "DSA / LeetCode", front: "21. Merge Two Sorted Lists — Easy (68.8%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/merge-two-sorted-lists\n\n**Difficulty:** Easy | **Acceptance:** 68.8%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, easy, leetcode" },
  { deck: "DSA / LeetCode", front: "23. Merge k Sorted Lists — Hard (60.4%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/merge-k-sorted-lists\n\n**Difficulty:** Hard | **Acceptance:** 60.4%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, hard, leetcode" },
  { deck: "DSA / LeetCode", front: "152. Maximum Product Subarray — Med. (37.0%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/maximum-product-subarray\n\n**Difficulty:** Med. | **Acceptance:** 37.0%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "153. Find Minimum in Rotated Sorted Array — Med. (55.2%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/find-minimum-in-rotated-sorted-array\n\n**Difficulty:** Med. | **Acceptance:** 55.2%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "33. Search in Rotated Sorted Array — Med. (45.5%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/search-in-rotated-sorted-array\n\n**Difficulty:** Med. | **Acceptance:** 45.5%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "417. Pacific Atlantic Water Flow — Med. (61.4%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/pacific-atlantic-water-flow\n\n**Difficulty:** Med. | **Acceptance:** 61.4%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "39. Combination Sum — Med. (77.1%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/combination-sum\n\n**Difficulty:** Med. | **Acceptance:** 77.1%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "295. Find Median from Data Stream — Hard (54.9%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/find-median-from-data-stream\n\n**Difficulty:** Hard | **Acceptance:** 54.9%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, hard, leetcode" },
  { deck: "DSA / LeetCode", front: "297. Serialize and Deserialize Binary Tree — Hard (61.1%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/serialize-and-deserialize-binary-tree\n\n**Difficulty:** Hard | **Acceptance:** 61.1%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, hard, leetcode" },
  { deck: "DSA / LeetCode", front: "424. Longest Repeating Character Replacement — Med. (60.5%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/longest-repeating-character-replacement\n\n**Difficulty:** Med. | **Acceptance:** 60.5%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "300. Longest Increasing Subsequence — Med. (59.9%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/longest-increasing-subsequence\n\n**Difficulty:** Med. | **Acceptance:** 59.9%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "48. Rotate Image — Med. (80.6%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/rotate-image\n\n**Difficulty:** Med. | **Acceptance:** 80.6%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "49. Group Anagrams — Med. (73.2%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/group-anagrams\n\n**Difficulty:** Med. | **Acceptance:** 73.2%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "435. Non-overlapping Intervals — Med. (57.6%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/non-overlapping-intervals\n\n**Difficulty:** Med. | **Acceptance:** 57.6%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "53. Maximum Subarray — Med. (53.8%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/maximum-subarray\n\n**Difficulty:** Med. | **Acceptance:** 53.8%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "54. Spiral Matrix — Med. (57.7%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/spiral-matrix\n\n**Difficulty:** Med. | **Acceptance:** 57.7%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "55. Jump Game — Med. (41.4%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/jump-game\n\n**Difficulty:** Med. | **Acceptance:** 41.4%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "56. Merge Intervals — Med. (52.7%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/merge-intervals\n\n**Difficulty:** Med. | **Acceptance:** 52.7%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "57. Insert Interval — Med. (45.9%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/insert-interval\n\n**Difficulty:** Med. | **Acceptance:** 45.9%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "572. Subtree of Another Tree — Easy (52.1%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/subtree-of-another-tree\n\n**Difficulty:** Easy | **Acceptance:** 52.1%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, easy, leetcode" },
  { deck: "DSA / LeetCode", front: "62. Unique Paths — Med. (67.2%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/unique-paths\n\n**Difficulty:** Med. | **Acceptance:** 67.2%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "190. Reverse Bits — Easy (69.2%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/reverse-bits\n\n**Difficulty:** Easy | **Acceptance:** 69.2%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, easy, leetcode" },
  { deck: "DSA / LeetCode", front: "191. Number of 1 Bits — Easy (77.4%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/number-of-1-bits\n\n**Difficulty:** Easy | **Acceptance:** 77.4%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, easy, leetcode" },
  { deck: "DSA / LeetCode", front: "322. Coin Change — Med. (49.0%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/coin-change\n\n**Difficulty:** Med. | **Acceptance:** 49.0%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "323. Number of Connected Components in an Undirected Graph — Med. (65.1%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph\n\n**Difficulty:** Med. | **Acceptance:** 65.1%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "70. Climbing Stairs — Easy (54.3%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/climbing-stairs\n\n**Difficulty:** Easy | **Acceptance:** 54.3%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, easy, leetcode" },
  { deck: "DSA / LeetCode", front: "198. House Robber — Med. (53.5%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/house-robber\n\n**Difficulty:** Med. | **Acceptance:** 53.5%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "200. Number of Islands — Med. (65.0%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/number-of-islands\n\n**Difficulty:** Med. | **Acceptance:** 65.0%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "73. Set Matrix Zeroes — Med. (63.5%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/set-matrix-zeroes\n\n**Difficulty:** Med. | **Acceptance:** 63.5%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "76. Minimum Window Substring — Hard (48.3%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/minimum-window-substring\n\n**Difficulty:** Hard | **Acceptance:** 48.3%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, hard, leetcode" },
  { deck: "DSA / LeetCode", front: "206. Reverse Linked List — Easy (81.0%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/reverse-linked-list\n\n**Difficulty:** Easy | **Acceptance:** 81.0%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, easy, leetcode" },
  { deck: "DSA / LeetCode", front: "79. Word Search — Med. (48.0%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/word-search\n\n**Difficulty:** Med. | **Acceptance:** 48.0%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "207. Course Schedule — Med. (52.1%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/course-schedule\n\n**Difficulty:** Med. | **Acceptance:** 52.1%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "208. Implement Trie (Prefix Tree) — Med. (70.0%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/implement-trie-prefix-tree\n\n**Difficulty:** Med. | **Acceptance:** 70.0%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "338. Counting Bits — Easy (80.8%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/counting-bits\n\n**Difficulty:** Easy | **Acceptance:** 80.8%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, easy, leetcode" },
  { deck: "DSA / LeetCode", front: "211. Design Add and Search Words Data Structure — Med. (48.9%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/design-add-and-search-words-data-structure\n\n**Difficulty:** Med. | **Acceptance:** 48.9%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "212. Word Search II — Hard (38.8%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/word-search-ii\n\n**Difficulty:** Hard | **Acceptance:** 38.8%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, hard, leetcode" },
  { deck: "DSA / LeetCode", front: "213. House Robber II — Med. (45.5%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/house-robber-ii\n\n**Difficulty:** Med. | **Acceptance:** 45.5%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "217. Contains Duplicate — Easy (64.7%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/contains-duplicate\n\n**Difficulty:** Easy | **Acceptance:** 64.7%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, easy, leetcode" },
  { deck: "DSA / LeetCode", front: "91. Decode Ways — Med. (38.5%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/decode-ways\n\n**Difficulty:** Med. | **Acceptance:** 38.5%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "347. Top K Frequent Elements — Med. (67.2%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/top-k-frequent-elements\n\n**Difficulty:** Med. | **Acceptance:** 67.2%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "253. Meeting Rooms II — Med. (52.8%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/meeting-rooms-ii\n\n**Difficulty:** Med. | **Acceptance:** 52.8%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "98. Validate Binary Search Tree — Med. (36.3%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/validate-binary-search-tree\n\n**Difficulty:** Med. | **Acceptance:** 36.3%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "226. Invert Binary Tree — Easy (80.4%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/invert-binary-tree\n\n**Difficulty:** Easy | **Acceptance:** 80.4%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, easy, leetcode" },
  { deck: "DSA / LeetCode", front: "100. Same Tree — Easy (67.9%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/same-tree\n\n**Difficulty:** Easy | **Acceptance:** 67.9%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, easy, leetcode" },
  { deck: "DSA / LeetCode", front: "1143. Longest Common Subsequence — Med. (59.5%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/longest-common-subsequence\n\n**Difficulty:** Med. | **Acceptance:** 59.5%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "102. Binary Tree Level Order Traversal — Med. (73.4%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/binary-tree-level-order-traversal\n\n**Difficulty:** Med. | **Acceptance:** 73.4%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "230. Kth Smallest Element in a BST — Med. (77.3%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/kth-smallest-element-in-a-bst\n\n**Difficulty:** Med. | **Acceptance:** 77.3%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "104. Maximum Depth of Binary Tree — Easy (78.6%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/maximum-depth-of-binary-tree\n\n**Difficulty:** Easy | **Acceptance:** 78.6%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, easy, leetcode" },
  { deck: "DSA / LeetCode", front: "105. Construct Binary Tree from Preorder and Inorder Traversal — Med. (69.4%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal\n\n**Difficulty:** Med. | **Acceptance:** 69.4%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "235. Lowest Common Ancestor of a Binary Search Tree — Med. (71.3%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree\n\n**Difficulty:** Med. | **Acceptance:** 71.3%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "238. Product of Array Except Self — Med. (69.2%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/product-of-array-except-self\n\n**Difficulty:** Med. | **Acceptance:** 69.2%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "242. Valid Anagram — Easy (68.6%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/valid-anagram\n\n**Difficulty:** Easy | **Acceptance:** 68.6%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, easy, leetcode" },
  { deck: "DSA / LeetCode", front: "371. Sum of Two Integers — Med. (55.8%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/sum-of-two-integers\n\n**Difficulty:** Med. | **Acceptance:** 55.8%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, medium, leetcode" },
  { deck: "DSA / LeetCode", front: "252. Meeting Rooms — Easy (59.5%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/meeting-rooms\n\n**Difficulty:** Easy | **Acceptance:** 59.5%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, easy, leetcode" },
  { deck: "DSA / LeetCode", front: "121. Best Time to Buy and Sell Stock — Easy (57.3%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/best-time-to-buy-and-sell-stock\n\n**Difficulty:** Easy | **Acceptance:** 57.3%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, easy, leetcode" },
  { deck: "DSA / LeetCode", front: "124. Binary Tree Maximum Path Sum — Hard (42.7%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/binary-tree-maximum-path-sum\n\n**Difficulty:** Hard | **Acceptance:** 42.7%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, hard, leetcode" },
  { deck: "DSA / LeetCode", front: "125. Valid Palindrome — Easy (54.2%) — Pattern? Approach?", back: "**Link:** https://leetcode.com/problems/valid-palindrome\n\n**Difficulty:** Easy | **Acceptance:** 54.2%\n\n**Recall:**\n- Pattern:\n- Approach:\n- Time/Space:\n- Edge cases:", tags: "blind75, easy, leetcode" },
];
